language:
    - cpp

branches:
    only:
        - master

compiler:
    - clang

before_install:
    - rvm use ruby-2.0.0-p648
    - mkdir build

install:
    - cd ./build
    - cmake ..
    - make

script:
    - ./src/common/common.out

os:
    - osx

notifications:
    email: true
    irc:
        channels:
            - chat.freenode.net#rubinius
        template:
            - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
    webhooks:
        urls: ~
        secure: !
        on_success: always
        on_failure: always
        on_start: always
